export default {
	Kosovë: {
		Prishtinë: 0,
		Mitrovicë: 0,
		Peja: 0,
		Prizeren: 0,
		Ferizaj: 0,
		Gjilan: 0,
		Gjakova: 0,
	},
	// Shqipëri: {
	// 	Tirana: 0,
	// 	Durrës: 0,
	// 	Vlorë: 0,
	// 	Elbasan: 0,
	// 	Shkodër: 0,
	// 	Fier: 0,
	// 	Korçë: 0,
	// 	Berat: 0,
	// 	Gjirokastër: 0,
	// 	Kukës: 0,
	// 	Lezhë: 0,
	// 	Dibër: 0,
	// },
	// 'Maqedoni Veriore': {
	// 	Shkupi: 0,
	// 	Tetova: 0,
	// 	Manastiri: 0,
	// 	Gostivari: 0,
	// 	Struga: 0,
	// 	Dibra: 0,
	// 	Kumanova: 0,
	// 	Ohri: 0,
	// 	Kërçova: 0,
	// },
} as const;
